### PR TITLE
Update Maxcontrol and runtime version

### PR DESCRIPTION
**Pull request by ghost**
- Update maxcontrol version to 0.5.4
- Update runtime to 46
- Fix appdata related issues
- Add required libsoup from shared modules
- Use cleanup command to reduce package size

### CODE REVIEW

**Comment by bbhtt** [comment]
cc @janbrummer

**Comment by janbrummer** [comment]
Thanks for your PR, I've took the chance to move your changes into the upstream project and will release a new version now. This should simplify your PR.

**Comment by janbrummer** [comment]
New release is available

**Comment by ghost** [comment]
@janbrummer I've added a cleanup command that reduce package size from 2.8MB to 1MB.

I couldn't test properly due to I don't have any Max device. 

resim

**Comment by ghost** [comment]
@barthalion I've updated Maxcontrol version to 0.5.4 and runtime version to 46.

**Comment by ghost** [comment]
Sent to upstream: https://gitlab.com/tabos/maxcontrol/-/merge_requests/4

**Pull request merged**
