### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by bbhtt**
Ping @janbrummer, please review when you have time, thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
Seems icon size is wrong:

`error: /srv/buildbot/worker/build-aarch64/build/builddir/export/share/icons/hicolor/scalable/apps/org.tabos.maxcontrol.svg is not a valid icon: Expected a square icon but got: 1003x1600`

**Comment by bbhtt** [comment]
I cannot reproduce the failure locally, so hopefully this works. This is how it looks with the new icon size:

image

Also opened https://gitlab.com/tabos/maxcontrol/-/issues/1

**Comment by janbrummer** [comment]
Thanks @bbhtt . Looks good so far.

**Comment by janbrummer** [comment]
I'll merge this and will add a todo to the official repository. Maybe you have some time to push your patch there as well? https://gitlab.com/tabos/maxcontrol

**Comment by bbhtt** [comment]
> I'll merge this and will add a todo to the official repository. Maybe you have some time to push your patch there as well? https://gitlab.com/tabos/maxcontrol

Sure, once I have the time but feel free to use them if I'm unavailable :)

**Pull request merged**
